openapi: 3.0.3
info:
  title: IDM APIs
  version: '2.1'
  description: APIs provided by the Vaillant Group Identity Management
servers:
  - url: https://identity-qa.vaillant-group.com/api
    description: QA
  - url: https://identity.vaillant-group.com/api
    description: Prod
paths:
  '/activate/b2c':
    post:
      summary: Activates a b2c user
      deprecated: true
      description: Please use /b2c/countries/{country}/brands/{brand}/users instead. Will be removed after 2022-12-31
      tags:
        - B2C
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/B2CActivation'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/B2CUserRegistrationResponse'
        '409':
          description: User is already activated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageResponse'
        '422':
          description: Error while validation of request object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '500':
          description: Unexpected internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/b2c/countries/{country}/brands/{brand}/users':
    post:
      summary: Registers a b2c user
      tags:
        - B2C
      parameters:
        - in: path
          name: country
          required: true
          schema:
            type: string
        - in: path
          name: brand
          required: true
          schema:
            type: string
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/B2CUserRegistrationRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/B2CUserRegistrationResponse'
        '409':
          description: User is already activated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageResponse'
        '422':
          description: Error while validation of request object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '500':
          description: Unexpected internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  '/b2c/countries/{country}/brands/{brand}/users/{email}':
    get:
      summary: Gets a b2c user
      deprecated: true
      description: Please use /b2c/countries/{country}/brands/{brand}/users/?q={email} instead. Will be removed after 2022-12-31
      tags:
        - B2C
      security:
        - basicAuth: []
      parameters:
        - in: path
          name: country
          required: true
          schema:
            type: string
        - in: path
          name: brand
          required: true
          schema:
            type: string
        - in: path
          name: email
          required: true
          schema:
            type: string
      responses:
        '200':
          description: When a user is found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/B2CUserResponse'
        '404':
          description: When the user does not exists for the provided brand/country
        '500':
          description: When an internal error occurs

  '/b2c/countries/{country}/brands/{brand}/users/':
    get:
      summary: Gets a b2c user
      tags:
        - B2C
      security:
        - basicAuth: []
      parameters:
        - in: path
          name: country
          required: true
          schema:
            type: string
        - in: path
          name: brand
          required: true
          schema:
            type: string
        - in: query
          name: email
          required: true
          schema:
            type: string
      responses:
        '200':
          description: All users matching all criteria. For lookup by email, there can be at most a single user in the result set
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/B2CUserResponse'
                nullable: false
        '404':
          description: When the user does not exists for the provided brand/country
        '500':
          description: When an internal error occurs

  '/activate/b2b':
    post:
      summary: Activates a b2b user
      description: Please use /b2b/countries/{country}/brands/{brand}/user-registrations instead. Will be removed after 2022-12-31
      deprecated: true
      tags:
        - B2B
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/B2BActivation'
      responses:
        '202':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/B2BUserRegistrationResponse'
          links:
            GetB2bStatus:
              operationId: getB2bStatus
              parameters:
                statusId: '$response.body#/id'
              description: >
                The `id` value returned in the response can be used as
                the `statusId` parameter in `GET /activate/b2b/status/{statusId}`.

        '422':
          description: Error while validation of request object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '500':
          description: Unexpected internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  '/b2b/countries/{country}/brands/{brand}/user-registrations':
    post:
      summary: Registers a b2b user
      description: The registration of a b2b user can take several seconds, up to minutes. This endpoint will only accept the registration request and process it asynchronously. Use the returned registration resource link to query registration status.
      tags:
        - B2B
      parameters:
        - in: path
          name: country
          required: true
          schema:
            type: string
        - in: path
          name: brand
          required: true
          schema:
            type: string
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/B2BActivation'
      responses:
        '202':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/B2BUserRegistrationResponse'
          links:
            GetB2bStatus:
              operationId: getB2BRegistrationStatus
              parameters:
                statusId: '$response.body#/id'
              description: >
                The `id` value returned in the response can be used as
                the `registrationId` parameter in `GET /b2b/countries/{country}/brands/{brand}/user-registrations/{registrationId}`.

        '422':
          description: Error while validation of request object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '500':
          description: Unexpected internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  '/activate/b2b/status/{statusId}':
    get:
      operationId: getB2bStatus
      summary: Gets the status of a b2b activation
      description: Please use /b2b/countries/{country}/brands/{brand}/user-registrations/{registrationId} instead. Will be removed after 2022-12-31
      deprecated: true
      tags:
        - B2B
      security:
        - basicAuth: []
      parameters:
        - in: path
          name: statusId
          description: Id of the b2b user activation
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: When status is RUNNING or COMPLETED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/B2BRegistrationStatusResponse'
        '404':
          description: When no status was found for the provided id
        '500':
          description: When the activation terminated exceptionally

  '/b2b/countries/{country}/brands/{brand}/user-registrations/{registrationId}':
    get:
      operationId: getB2BRegistrationStatus
      summary: Gets the status of a b2b registration
      tags:
        - B2B
      security:
        - basicAuth: []
      parameters:
        - in: path
          name: country
          required: true
          schema:
            type: string
        - in: path
          name: brand
          required: true
          schema:
            type: string
        - in: path
          name: registrationId
          description: Id of the b2b user registration
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: When status is RUNNING or COMPLETED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/B2BRegistrationStatusResponse'
        '404':
          description: When no status was found for the provided id
        '500':
          description: When the activation terminated exceptionally

  '/api-developer/users':
    post:
      summary: Registers a user for the API Developer Portal
      tags:
        - API-Developer
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiDeveloperUserRegistrationRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiDeveloperUserRegistrationResponse'
        '409':
          description: User is already activated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageResponse'
        '422':
          description: Error while validation of request object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '500':
          description: Unexpected internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  schemas:
    B2CActivation:
      type: object
      deprecated: true
      description: Will be removed after 2022-12-31
      properties:
        firstname:
          type: string
          nullable: true
          description: Is used in the activation email
        lastname:
          type: string
          nullable: true
          description: Is used in the activation email
        email:
          type: string
          nullable: false
        brand:
          type: string
          nullable: false
        country:
          type: string
          nullable: false
        brandDetailContactId:
          type: string
          description: Brand detail contact id of contact to be activated
          nullable: false
        locale:
          type: string
          description: Language of the user e.g. 'fr' or 'nl'
          nullable: false
        clientId:
          type: string
          description: IDM client id
          nullable: false
        redirectUri:
          type: string
          description: The URI where the user gets redirect to after successful activation.
          nullable: false

    B2CUserRegistrationRequest:
      type: object
      properties:
        firstname:
          type: string
          nullable: true
          description: Is used in the activation email
        lastname:
          type: string
          nullable: true
          description: Is used in the activation email
        email:
          type: string
          nullable: false
        brandDetailContactId:
          type: string
          description: Brand detail contact id of contact to be activated
          nullable: false
        locale:
          type: string
          description: Language of the user e.g. 'fr' or 'nl'
          nullable: false
        clientId:
          type: string
          description: IDM client id
          nullable: false
        redirectUri:
          type: string
          description: The URI where the user gets redirect to after successful activation.
          nullable: false

    B2BActivation:
      type: object
      deprecated: true
      description: Will be removed after 2022-12-31
      properties:
        email:
          type: string
          nullable: false
        brand:
          type: string
          nullable: false
        country:
          type: string
          nullable: false
        locale:
          type: string
          nullable: false
        brandDetailContactId:
          type: string
          description: Brand detail contact id of contact to be activated
          nullable: false
        salutation:
          type: string
          nullable: true
        firstname:
          type: string
          nullable: true
        lastname:
          type: string
          nullable: true
        clientId:
          type: string
          description: IDM client id
          nullable: true
        redirectUri:
          type: string
          description: The URI where the user gets redirect to after successful activation.
          nullable: true

    B2BUserRegistrationRequest:
      type: object
      properties:
        email:
          type: string
          nullable: false
        locale:
          type: string
          nullable: false
        brandDetailContactId:
          type: string
          description: Brand detail contact id of contact to be activated
          nullable: false
        salutation:
          type: string
          nullable: true
        firstname:
          type: string
          nullable: true
        lastname:
          type: string
          nullable: true
        clientId:
          type: string
          description: IDM client id
          nullable: true
        redirectUri:
          type: string
          description: The URI where the user gets redirect to after successful activation.
          nullable: true

    ApiDeveloperUserRegistrationRequest:
      type: object
      properties:
        email:
          type: string
          nullable: false
        username:
          type: string
          nullable: false
        firstname:
          type: string
          nullable: false
        lastname:
          type: string
          nullable: false
        country:
          type: string
          nullable: true
        clientId:
          type: string
          description: IDM client id
          nullable: false
        redirectUri:
          type: string
          description: The URI where the user gets redirect to after successful activation.
          nullable: false

    B2CUserRegistrationResponse:
      type: object
      properties:
        userId:
          type: string
          description: IDM Id of the user
          nullable: false


    B2CUserResponse:
      type: object
      properties:
        userId:
          type: string
          description: IDM Id of the user
          nullable: false
        email:
          type: string
          nullable: false
        brandDetailContactId:
          type: string
          nullable: false
        activated:
          type: boolean
          description: Indicates whether the user completed the activation process

    B2BUserRegistrationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
          description: Id of the activation status
          nullable: false
        href:
          type: string
          description: link to fetch the status
          example: /activate/b2b/status/3fa85f64-5717-4562-b3fc-2c963f66afa6
          nullable: false

    ApiDeveloperUserRegistrationResponse:
      type: object
      properties:
        userId:
          type: string
          description: IDM Id of the user
          nullable: false

    B2BRegistrationStatusResponse:
      type: object
      properties:
        status:
          type: string
          enum: [RUNNING, COMPLETED, ERROR]
          description: IDM Id of the user
          nullable: false

    ValidationErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
          nullable: false

    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          example: 500
          description: HTTP Status code
          nullable: false
        message:
          type: string
          nullable: false

    ErrorMessageResponse:
      type: object
      properties:
        message:
          type: string
          nullable: false

