openapi: 3.0.1
info:
  title: File upload
  description: "[WORK IN PROGRESS] Provides functionality to store one or multiple\
    \ files. A malware check will be performed before storing files. Infection details\
    \ are returned, if malware is detected."
  version: "0.1"
servers:
- url: https://dsp-fileupload.azurewebsites.net/
  description: Azure Function App
  variables: {}
security:
- code: []
tags:
- name: File upload
paths:
  /api/files/analyse:
    post:
      tags:
      - File upload
      summary: Scan the uploaded files for malware
      operationId: analyseFileDocumentation
      parameters:
      - name: code
        in: query
        description: API key
        required: true
        schema:
          type: string
      requestBody:
        description: Files to be checked
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                ? ""
                : minItems: 1
                  type: array
                  items:
                    type: string
                    format: binary
            encoding:
              file:
                contentType: application/octet-stream
                headers:
                  Content-Disposition:
                    description: Content-Disposition header
                    required: true
                    style: simple
                    schema:
                      pattern: "^form-data; name=\"[^\"]+\"; filename=\"[^\"]+\"$"
                      type: string
                      default: form-data; name="test_input"; filename="test_input"
        required: true
      responses:
        "200":
          description: "File scan complete, no infections found"
          content:
            application/json:
              schema:
                type: string
              example:
                image1.jpg: NOT_INFECTED
                image2.jpg: NOT_INFECTED
        "400":
          description: Missing filename
        "422":
          description: Malware scan found infected files
          content:
            application/json:
              schema:
                type: string
              example:
                image1.jpg: NOT_INFECTED
                image2.jpg: INFECTED
      security:
      - code: []
  /api/files/upload:
    post:
      tags:
      - File upload
      summary: Scan the uploaded files for malware and store in Salesforce
      operationId: uploadFileDocumentation
      parameters:
      - name: code
        in: query
        description: API key
        required: true
        schema:
          type: string
      - name: recordID
        in: query
        description: Record ID
        required: true
        schema:
          type: string
      requestBody:
        description: Files to be uploaded
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                ? ""
                : minItems: 1
                  type: array
                  items:
                    type: string
                    format: binary
            encoding:
              file:
                contentType: application/octet-stream
                headers:
                  Content-Disposition:
                    description: Content-Disposition header
                    required: true
                    style: simple
                    schema:
                      pattern: "^form-data; name=\"[^\"]+\"; filename=\"[^\"]+\"$"
                      type: string
                      default: form-data; name="test_input"; filename="test_input"
        required: true
      responses:
        "200":
          description: File upload OK
          content:
            application/json:
              schema:
                type: string
              example:
                image1.jpg: UPLOADED
                image2.jpg: UPLOADED
        "400":
          description: Missing filename
        "422":
          description: Malware scan found infected files
          content:
            application/json:
              schema:
                type: string
              example:
                image1.jpg: UPLOADED
                image2.jpg: INFECTED
        "500":
          description: Upload error of at least one file
          content:
            application/json:
              schema:
                type: string
              example:
                image1.jpg: UPLOADED
                image2.jpg: UPLOAD_ERROR
      security:
      - code: []
components:
  securitySchemes:
    code:
      type: apiKey
      name: code
      in: query
