openapi: 3.0.1
info:
  title: File upload
  description: "Provides functionality to store one or multiple files. A malware check\
    \ will be performed before storing files. Infection details are returned, if malware\
    \ is detected."
  version: "0.1"
servers:
- url: https://dsp-fileupload.azurewebsites.net/
  description: Azure Function App
  variables: {}
security:
- API kwy: []
paths:
  /api/analyse-file:
    post:
      summary: Scan the uploaded files for malware
      operationId: run
      requestBody:
        description: Files to be checked
        content:
          multipart/form-data: {}
        required: true
      responses:
        "200":
          description: File(s) OK
        "400":
          description: "Empty body, file size limit exceeded"
        "422":
          description: Details on the File(s) infected
          content:
            application/json: {}
components:
  schemas:
    HttpResponseMessage:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        status:
          $ref: '#/components/schemas/HttpStatusType'
        body:
          type: object
    HttpStatusType:
      type: object
    HttpRequestMessageOptionalByte[]:
      type: object
      properties:
        headers:
          type: object
          additionalProperties:
            type: string
        queryParameters:
          type: object
          additionalProperties:
            type: string
        httpMethod:
          type: string
          enum:
          - GET
          - HEAD
          - POST
          - PUT
          - DELETE
          - CONNECT
          - OPTIONS
          - TRACE
          - PATCH
        uri:
          type: string
          format: uri
        body:
          type: array
          items:
            type: string
            format: byte
    ExecutionContext:
      type: object
      properties:
        logger:
          type: object
          properties:
            name:
              type: string
            filter:
              type: object
            resourceBundleName:
              type: string
            level:
              type: object
              properties:
                name:
                  type: string
                resourceBundleName:
                  type: string
                localizedName:
                  type: string
            handlers:
              type: array
              items:
                type: object
                properties:
                  filter:
                    type: object
                  formatter:
                    type: object
                  errorManager:
                    type: object
                  encoding:
                    type: string
                  level:
                    type: object
                    properties:
                      name:
                        type: string
                      resourceBundleName:
                        type: string
                      localizedName:
                        type: string
            useParentHandlers:
              type: boolean
            resourceBundle:
              type: object
              properties:
                locale:
                  type: object
                  properties:
                    language:
                      type: string
                    script:
                      type: string
                    variant:
                      type: string
                    displayName:
                      type: string
                    country:
                      type: string
                    unicodeLocaleAttributes:
                      uniqueItems: true
                      type: array
                      items:
                        type: string
                    unicodeLocaleKeys:
                      uniqueItems: true
                      type: array
                      items:
                        type: string
                    displayLanguage:
                      type: string
                    displayScript:
                      type: string
                    displayCountry:
                      type: string
                    displayVariant:
                      type: string
                    extensionKeys:
                      uniqueItems: true
                      type: array
                      items:
                        type: string
                    iso3Language:
                      type: string
                    iso3Country:
                      type: string
                keys:
                  type: object
                baseBundleName:
                  type: string
        retryContext:
          $ref: '#/components/schemas/RetryContext'
        traceContext:
          $ref: '#/components/schemas/TraceContext'
        invocationId:
          type: string
        functionName:
          type: string
    RetryContext:
      type: object
      properties:
        exception:
          $ref: '#/components/schemas/RpcException'
        retrycount:
          type: integer
          format: int32
        maxretrycount:
          type: integer
          format: int32
    RpcException:
      type: object
      properties:
        message:
          type: string
        source:
          type: string
        stacktrace:
          type: string
    TraceContext:
      type: object
      properties:
        attributes:
          type: object
          additionalProperties:
            type: string
        traceparent:
          type: string
        tracestate:
          type: string
